Global:
  debug: false
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/placa_br_model
  save_epoch_step: 1
  eval_batch_step: [100, 500]
  cal_metric_during_train: true
  pretrained_model: ./dataset/pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words/en/word_1.png
  character_dict_path: ./dataset/finetuning/caracteres_placas_br.txt
  max_text_length: 8
  infer_model: false
  use_space_char: false
  distributed: false
  save_res_path: ./output/rec/predicts_placa_br.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ""
    label_file_list:
      - ./dataset/finetuning/train.txt
    transforms:
      - CTCLabelEncode:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - SVTRRecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
    ratio_list: [1.0]
  loader:
    shuffle: true
    batch_size_per_card: 16
    drop_last: true
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ""
    label_file_list:
      - ./dataset/finetuning/eval.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - SVTRRecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
    ratio_list: [1.0]
  loader:
    shuffle: false
    batch_size_per_card: 16
    drop_last: false
    num_workers: 2